name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 4 * * MON'

jobs:
  CI:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        distro: ['ubuntu:latest']
        backend: ["SERIAL", "OPENMP"]
        arborx: ["ArborX", "NoArborX"]
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ecp-copa/ci-containers/${{ matrix.distro }}
    steps:
      - name: Checkout kokkos
        uses: actions/checkout@v2.2.0
        with:
          repository: kokkos/kokkos
          ref: 3.6.01
          path: kokkos
      - name: Build kokkos
        working-directory: kokkos
        run: |
          cmake -B build \
            -DCMAKE_INSTALL_PREFIX=$HOME/kokkos \
            -DKokkos_CXX_STANDARD=17 \
            -DKokkos_ENABLE_${{ matrix.backend }}=ON
          cmake --build build --parallel 2
          cmake --install build
      - name: Checkout arborx
        if: ${{ matrix.arborx == 'ArborX' }}
        uses: actions/checkout@v2.2.0
        with:
          repository: arborx/ArborX
          ref: v1.2
          path: arborx
      - name: Build arborx
        if: ${{ matrix.arborx == 'ArborX' }}
        working-directory: arborx
        run: |
          cmake -B build \
            -DCMAKE_PREFIX_PATH=${HOME}/kokkos \
            -DCMAKE_INSTALL_PREFIX=$HOME/arborx
          cmake --build build --parallel 2
          cmake --install build
      - name: Checkout Cabana
        uses: actions/checkout@v2.2.0
        with:
          repository: ECP-copa/Cabana
          ref: master
          path: Cabana
      - name: Build Cabana
        working-directory: Cabana
        run: |
          [[ ${{ matrix.arborx }} == 'ArborX' ]] && cmake_opts+=( -DCabana_REQUIRE_ARBORX=ON )
          cmake -B build \
          -DCMAKE_INSTALL_PREFIX=$HOME/Cabana \
          -DCMAKE_PREFIX_PATH="$HOME/kokkos;$HOME/arborx" \
          -DCabana_REQUIRE_${{ matrix.backend }}=ON \
          ${cmake_opts[@]}
          cmake --build build --parallel 2
          cmake --install build
      - name: Checkout code
        uses: actions/checkout@v2.2.0
      - name: Build
        run: |
          cmake -B build -DCMAKE_PREFIX_PATH="$HOME/Cabana"
          cmake --build build --parallel 2
